stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
    - pre-commit install
  script:
    - pre-commit run --all-files
  only:
    - merge_requests
    - main
    - develop

test:
  stage: test
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
  script:
    - coverage run --source=app -m pytest -v tests
    - coverage report -m
    - coverage html
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 week
  only:
    - merge_requests
    - main
    - develop

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t python-devops-template .
    # - docker tag python-devops-template:latest your-registry/python-devops-template:latest
  only:
    - main
    - develop
