stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
    - pre-commit install
  script:
    - pre-commit run --all-files
  only:
    - main

test:
  pages: true
  stage: test
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
  script:
    - coverage run --source=app -m pytest -v tests
    - coverage report -m
    - coverage html
    - mkdir public
    - cp -r htmlcov/* public/
  artifacts:
    paths:
      - htmlcov/
  only:
    - main

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t python-devops-template .
  only:
    - main
